import Head from "next/head";
import TimerContainer from "@/components/TimerContainer";

export default function Home() {
  return (
    <div className="bg-slate-100 px-10 pt-2 text-slate-900">
      <Head>
        <title>Pomogrids</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <TimerContainer />
    </div>
  );
}
