import Head from "next/head";
import BaseButton from "@/components/BaseButton";
import { Inter } from "next/font/google";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pomogrids</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../../public/images/logo.png" />
      </Head>
      <h1>Main</h1>
    </>
  );
}
